name: mi_country_picker
description: Flutter package for selecting country codes. Offers multiple modes for picker and supports locale in 70 languages.
version: 0.0.3
repository: https://github.com/Mindinventory/mi_country_picker
issue_tracker: https://github.com/Mindinventory/mi_country_picker/issues

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - lib/assets/flags/
    - lib/assets/icons/
    - packages/mi_country_picker/src/i18n/af.json
    - packages/mi_country_picker/src/i18n/am.json
    - packages/mi_country_picker/src/i18n/ha.json
    - packages/mi_country_picker/src/i18n/ku.json
    - packages/mi_country_picker/src/i18n/ml.json
    - packages/mi_country_picker/src/i18n/no.json
    - packages/mi_country_picker/src/i18n/ps.json
    - packages/mi_country_picker/src/i18n/sd.json
    - packages/mi_country_picker/src/i18n/so.json
    - packages/mi_country_picker/src/i18n/sq.json
    - packages/mi_country_picker/src/i18n/ta.json
    - packages/mi_country_picker/src/i18n/tg.json
    - packages/mi_country_picker/src/i18n/tt.json
    - packages/mi_country_picker/src/i18n/ug.json
    - packages/mi_country_picker/src/i18n/ur.json
    - packages/mi_country_picker/src/i18n/vi.json
    - packages/mi_country_picker/src/i18n/ar.json
    - packages/mi_country_picker/src/i18n/az.json
    - packages/mi_country_picker/src/i18n/be.json
    - packages/mi_country_picker/src/i18n/bg.json
    - packages/mi_country_picker/src/i18n/bn.json
    - packages/mi_country_picker/src/i18n/bs.json
    - packages/mi_country_picker/src/i18n/ca.json
    - packages/mi_country_picker/src/i18n/cs.json
    - packages/mi_country_picker/src/i18n/da.json
    - packages/mi_country_picker/src/i18n/de.json
    - packages/mi_country_picker/src/i18n/el.json
    - packages/mi_country_picker/src/i18n/en.json
    - packages/mi_country_picker/src/i18n/es.json
    - packages/mi_country_picker/src/i18n/et.json
    - packages/mi_country_picker/src/i18n/fa.json
    - packages/mi_country_picker/src/i18n/fi.json
    - packages/mi_country_picker/src/i18n/fr.json
    - packages/mi_country_picker/src/i18n/gl.json
    - packages/mi_country_picker/src/i18n/el.json
    - packages/mi_country_picker/src/i18n/he.json
    - packages/mi_country_picker/src/i18n/hi.json
    - packages/mi_country_picker/src/i18n/hr.json
    - packages/mi_country_picker/src/i18n/hu.json
    - packages/mi_country_picker/src/i18n/hy.json
    - packages/mi_country_picker/src/i18n/id.json
    - packages/mi_country_picker/src/i18n/is.json
    - packages/mi_country_picker/src/i18n/it.json
    - packages/mi_country_picker/src/i18n/ja.json
    - packages/mi_country_picker/src/i18n/ka.json
    - packages/mi_country_picker/src/i18n/kk.json
    - packages/mi_country_picker/src/i18n/km.json
    - packages/mi_country_picker/src/i18n/ko.json
    - packages/mi_country_picker/src/i18n/ky.json
    - packages/mi_country_picker/src/i18n/lt.json
    - packages/mi_country_picker/src/i18n/lv.json
    - packages/mi_country_picker/src/i18n/mk.json
    - packages/mi_country_picker/src/i18n/mn.json
    - packages/mi_country_picker/src/i18n/ms.json
    - packages/mi_country_picker/src/i18n/nb.json
    - packages/mi_country_picker/src/i18n/nl.json
    - packages/mi_country_picker/src/i18n/nn.json
    - packages/mi_country_picker/src/i18n/pl.json
    - packages/mi_country_picker/src/i18n/pt.json
    - packages/mi_country_picker/src/i18n/ro.json
    - packages/mi_country_picker/src/i18n/ru.json
    - packages/mi_country_picker/src/i18n/sk.json
    - packages/mi_country_picker/src/i18n/sl.json
    - packages/mi_country_picker/src/i18n/sr.json
    - packages/mi_country_picker/src/i18n/sv.json
    - packages/mi_country_picker/src/i18n/th.json
    - packages/mi_country_picker/src/i18n/tr.json
    - packages/mi_country_picker/src/i18n/uk.json
    - packages/mi_country_picker/src/i18n/uz.json
    - packages/mi_country_picker/src/i18n/zh.json

